export interface Brand {
  name: string
  logo: string
}

/* ---------------- 1. PARTNERS (35 Brands) ---------------- */
export const PARTNERS: Brand[] = [
  { name: "Pampanga Provincial Board", logo: "/business_logos/partners/Pampanga Provincial Board.png" },
  { name: "Angeles City", logo: "/business_logos/partners/Angeles City.png" },
  { name: "Experience, Live, Love Angeles", logo: "/business_logos/partners/Angeles City_2.png" },
  { name: "clArk", logo: "/business_logos/partners/clArk.png" },
  { name: "Clark Development Corporation", logo: "/business_logos/partners/Clark Development Corporation.png" },
  { name: "Department of Trade & Industry", logo: "/business_logos/partners/Department of Trade & Industry.png" },
  { name: "DOST Pampanga", logo: "/business_logos/partners/DOST Pampanga.png" },
  { name: "La Germania", logo: "/business_logos/partners/La Germania.png" },
  { name: "Peotraco Food Inc.", logo: "/business_logos/partners/Peotraco Food Inc..png" },
  { name: "Fly Ace Food Service", logo: "/business_logos/partners/Fly Ace Food Service.png" },
  { name: "Uni-Fab Metal Industries", logo: "/business_logos/partners/Uni-Fab Metal Industries.png" },
  { name: "Dona Elena", logo: "/business_logos/partners/Dona Elena.png" },
  { name: "Global Pacific", logo: "/business_logos/partners/Global Pacific.png" },
  { name: "Kraft Heinz", logo: "/business_logos/partners/Kraft Heinz.png" },
  { name: "DLA Naturals", logo: "/business_logos/partners/DLA Naturals.png" },
  { name: "masflex Cookware & Kitchenware", logo: "/business_logos/partners/masflex Cookware & Kitchenware.png" },
  { name: "Sundae Bar by Echo Treats", logo: "/business_logos/partners/Sundae Bar by Echo Treats.png" },
  { name: "Eastwest Ageas Insurance", logo: "/business_logos/partners/Eastwest Ageas Insurance.png" },
  { name: "Cohrep", logo: "/business_logos/partners/Cohrep.png" },
  { name: "NU Clark", logo: "/business_logos/partners/NU Clark.png" },
  { name: "City College of Angeles", logo: "/business_logos/partners/City College of Angeles.png" },
  { name: "Holy Angel University Pampanga", logo: "/business_logos/partners/Holy Angel University Pampanga.png" },
  { name: "FEU Pampanga", logo: "/business_logos/partners/FEU Pampanga.png" },
  { name: "Etcor Educational Research Center", logo: "/business_logos/partners/Etcor Educational Research Center.png" },
  { name: "Pampanga Business Circle", logo: "/business_logos/partners/Pampanga Business Circle.png" },
  { name: "PCCI Tarlac", logo: "/business_logos/partners/PCCI Tarlac.png" },
  { name: "Metro Angeles Chamber of Commercial & Industry Inc.", logo: "/business_logos/partners/Metro Angeles Chamber of Commercial & Industry Inc..png" },
  { name: "BNI Central Luzon 1", logo: "/business_logos/partners/BNI Central Luzon 1.png" },
  { name: "Wedding Suppliers Association of the Philippines", logo: "/business_logos/partners/Wedding Suppliers Association of the Philippines.png" },
  { name: "Central Luzon Media Association Pampanga Chapter", logo: "/business_logos/partners/Central Luzon Media Association Pampanga Chapter.png" },
  { name: "CLTV 36", logo: "/business_logos/partners/CLTV 36.png" },
  { name: "Reaching Beyond Channels", logo: "/business_logos/partners/Reaching Beyond Channels.png" },
  { name: "RW 95.1 FM", logo: "/business_logos/partners/RW 95.1 FM.png" },
  { name: "Pampanga Press Club", logo: "/business_logos/partners/Pampanga Press Club.png" },
  { name: "JPG Exhibition Booth Rentals", logo: "/business_logos/partners/JPG Exhibition Booth Rentals.png" },
]

/* ---------------- 2. SPONSORS (13 Brands) ---------------- */
export const SPONSORS: Brand[] = [
  { name: "Savers Group Holdings Inc.", logo: "/business_logos/sponsors/Savers Group Holdings Inc.png" },
  { name: "GCash", logo: "/business_logos/sponsors/GCash.png" },
  { name: "Department of Tourism", logo: "/business_logos/sponsors/Department of Tourism.png" },
  { name: "Central Luzon", logo: "/business_logos/sponsors/Central Luzon.png" },
  { name: "Clark International Airport Corporation", logo: "/business_logos/sponsors/Clark International Airport Corporation.png" },
  { name: "Maki Mura Ramen Bar", logo: "/business_logos/sponsors/Maki Mura Ramen Bar.png" },
  { name: "Crabs n Crack Seafood House", logo: "/business_logos/sponsors/Crabs n Crack Seafood House.png" },
  { name: "PLDT Enterprise", logo: "/business_logos/sponsors/PLDT Enterprise.png" },
  { name: "Romac Services & Trading Company Inc.", logo: "/business_logos/sponsors/Romac Services & Trading Company Inc..png" },
  { name: "AF Ventures Inc.", logo: "/business_logos/sponsors/AF Ventures Inc..png" },
  { name: "ADM Catering", logo: "/business_logos/sponsors/ADM Catering.png" },
  { name: "Esme Restaurant", logo: "/business_logos/sponsors/Esme Restaurant.png" },
  { name: "Asuncion's Private Dining", logo: "/business_logos/sponsors/Asuncion's Private Dining.png" },
]

/* ---------------- 3. EXHIBITORS (80 Brands) ---------------- */
export const EXHIBITORS: Brand[] = [
  { name: "bcmm", logo: "/business_logos/exhibitor/bcmm.png" },
  { name: "Best Western Plus Hotel Subic", logo: "/business_logos/exhibitor/Best Western Plus Hotel Subic.png" },
  { name: "Best Western Plus Metro Clark", logo: "/business_logos/exhibitor/Best Western Plus Metro Clark.png" },
  { name: "Cactus Jack Smokehouse", logo: "/business_logos/exhibitor/Cactus Jack Smokehouse.png" },
  { name: "Cafe Sebastian", logo: "/business_logos/exhibitor/Cafe Sebastian.png" },
  { name: "Camel", logo: "/business_logos/exhibitor/Camel.png" },
  { name: "Tiandy", logo: "/business_logos/exhibitor/Tiandy.png" },
  { name: "Triple LMG Trading", logo: "/business_logos/exhibitor/Triple LMG Trading.png" },
  { name: "Century Pacific Food Solutions", logo: "/business_logos/exhibitor/Century Pacific Food Solutions - Elevate Enterprises Inc..png" },
  { name: "Polland", logo: "/business_logos/exhibitor/Polland.png" },
  { name: "Condura", logo: "/business_logos/exhibitor/Condura.png" },
  { name: "Whirlpool", logo: "/business_logos/exhibitor/Whirlpool.png" },
  { name: "Viktor Brew + Bar", logo: "/business_logos/exhibitor/Viktor Brew + Bar.png" },
  { name: "Dayap Philippines", logo: "/business_logos/exhibitor/Dayap Philippines.png" },
  { name: "Sundae Bar By Echo Treats", logo: "/business_logos/exhibitor/Sundae Bar By Echo Treats.png" },
  { name: "Mekeni", logo: "/business_logos/exhibitor/Mekeni.png" },
  { name: "Dara Consulting", logo: "/business_logos/exhibitor/Dara Consulting.png" },
  { name: "Consistent Frozen Solutions", logo: "/business_logos/exhibitor/Consistent Frozen Solutions.png" },
  { name: "Angeles City", logo: "/business_logos/exhibitor/Angeles City.png" },
  { name: "Migoy's Burger", logo: "/business_logos/exhibitor/Migoy's Burger.png" },
  { name: "Isabel Frozen Products", logo: "/business_logos/exhibitor/Isabel Frozen Products.png" },
  { name: "Hapag Scan Order Pay", logo: "/business_logos/exhibitor/Hapag Scan Order Pay.png" },
  { name: "Casa Esmeralda", logo: "/business_logos/exhibitor/Casa Esmeralda.png" },
  { name: "Metrobank", logo: "/business_logos/exhibitor/Metrobank.png" },
  { name: "gud is better", logo: "/business_logos/exhibitor/gud is better.png" },
  { name: "Hannah Marielle's Bakes & Cakes", logo: "/business_logos/exhibitor/Hannah Marielle's Bakes & Cakes.png" },
  { name: "Trisco Foods", logo: "/business_logos/exhibitor/Trisco Foods.png" },
  { name: "Venezia", logo: "/business_logos/exhibitor/Venezia.png" },
  { name: "Switch Ecomobility", logo: "/business_logos/exhibitor/Switch Ecomobility.png" },
  { name: "WiiArts", logo: "/business_logos/exhibitor/WiiArts.png" },
  { name: "Home Kitchen", logo: "/business_logos/exhibitor/Home Kitchen.png" },
  { name: "Jack's Pool Bar", logo: "/business_logos/exhibitor/Jack's Pool Bar.png" },
  { name: "Luka's Butter Steaks", logo: "/business_logos/exhibitor/Luka's Butter Steaks.png" },
  { name: "Maki Mura", logo: "/business_logos/exhibitor/Maki Mura.png" },
  { name: "1st Mega Saver", logo: "/business_logos/exhibitor/1st Mega Saver.png" },
  { name: "Namari Japanese Bistro", logo: "/business_logos/exhibitor/Namari Japanese Bistro.png" },
  { name: "Makuru Japanese Wraps & Rolls", logo: "/business_logos/exhibitor/Makuru Japanese Wraps & Rolls.png" },
  { name: "Monaco", logo: "/business_logos/exhibitor/Monaco.png" },
  { name: "Spencers Fusion", logo: "/business_logos/exhibitor/Spencers Fusion.png" },
  { name: "Caution Coffee", logo: "/business_logos/exhibitor/Caution Coffee.png" },
  { name: "Prime Pacific Foods Corporation", logo: "/business_logos/exhibitor/Prime Pacific Foods Corporation.png" },
  { name: "Legend Hong Kong Seafood Restaurant", logo: "/business_logos/exhibitor/Legend Hong Kong Seafood Restaurant.png" },
  { name: "pyc Foods Corporation", logo: "/business_logos/exhibitor/pyc Foods Corporation.png" },
  { name: "LG", logo: "/business_logos/exhibitor/LG.png" },
  { name: "Seachamp", logo: "/business_logos/exhibitor/Seachamp.png" },
  { name: "Liway Enterprises Inc.", logo: "/business_logos/exhibitor/Liway Enterprises Inc..png" },
  { name: "smart living", logo: "/business_logos/exhibitor/smart living.png" },
  { name: "Kasuko", logo: "/business_logos/exhibitor/Kasuko.png" },
  { name: "Savers Industrial & Building Solutions", logo: "/business_logos/exhibitor/Savers Industrial & Building Solutions.png" },
  { name: "Savers Group Holdings Inc.", logo: "/business_logos/exhibitor/Savers Group Holdings Inc.png" },
  { name: "Sunshine Clean Greens", logo: "/business_logos/exhibitor/Sunshine Clean Greens.png" },
  { name: "Farm to Table", logo: "/business_logos/exhibitor/Farm to Table.png" },
  { name: "Asuncion's", logo: "/business_logos/exhibitor/Asuncion's Private Dining.png" },
  { name: "AF Ventures Inc.", logo: "/business_logos/exhibitor/AF Ventures Inc..png" },
  { name: "ADM Catering", logo: "/business_logos/exhibitor/ADM Catering.png" },
  { name: "Esme", logo: "/business_logos/exhibitor/Esme Restaurant.png" },
  { name: "Fortune Tea House", logo: "/business_logos/exhibitor/Fortune Tea House.png" },
  { name: "Tecnogas Technik", logo: "/business_logos/exhibitor/Tecnogas Technik.png" },
  { name: "Allie Steel Premium Metal Cabinet", logo: "/business_logos/exhibitor/Allie Steel Premium Metal Cabinet.png" },
  { name: "BNI Central Luzon 1", logo: "/business_logos/exhibitor/BNI Central Luzon 1.png" },
  { name: "Elektro Kuche", logo: "/business_logos/exhibitor/Elektro Kuche.png" },
  { name: "Fujidenzo", logo: "/business_logos/exhibitor/Fujidenzo.png" },
  { name: "JDNB Enterprise Corporation", logo: "/business_logos/exhibitor/JDNB Enterprise Corporation.png" },
  { name: "Lugaw ni Bossing", logo: "/business_logos/exhibitor/Lugaw ni Bossing.png" },
  { name: "American Ribs & Wings", logo: "/business_logos/exhibitor/American Ribs & Wings.png" },
  { name: "kape kaia", logo: "/business_logos/exhibitor/kape kaia.png" },
  { name: "cloud9", logo: "/business_logos/exhibitor/cloud9.png" },
  { name: "92 parameters", logo: "/business_logos/exhibitor/92 parameters.png" },
  { name: "leaf & bean slow bar", logo: "/business_logos/exhibitor/leaf & bean slow bar.png" },
  { name: "Ceremo", logo: "/business_logos/exhibitor/Ceremo.png" },
  { name: "Lilim", logo: "/business_logos/exhibitor/Lilim.png" },
  { name: "Artisanos Specialty Coffee & Matcha", logo: "/business_logos/exhibitor/Artisanos Specialty Coffee & Matcha.png" },
  { name: "hakone Matcha + Mochi", logo: "/business_logos/exhibitor/hakone Matcha + Mochi.png" },
  { name: "kismet", logo: "/business_logos/exhibitor/kismet.png" },
  { name: "kokorobi", logo: "/business_logos/exhibitor/kokorobi.png" },
  { name: "matchabaa", logo: "/business_logos/exhibitor/matchabaa.png" },
  { name: "Slow Sunday", logo: "/business_logos/exhibitor/Slow Sunday.png" },
  { name: "Whisk & Sip", logo: "/business_logos/exhibitor/Whisk & Sip.png" },
  { name: "Silung Coffee", logo: "/business_logos/exhibitor/Silung Coffee.png" },
  { name: "M2", logo: "/business_logos/exhibitor/M2.png" },
]