import { getAssetUrl } from "@/lib/assets"

export interface Brand {
  name: string
  logo: string
}

const withStorageUrl = (items: Brand[]): Brand[] =>
  items.map((b) => ({ ...b, logo: getAssetUrl(b.logo) }))

/* ---------------- 1. PARTNERS (35 Brands) ---------------- */
export const PARTNERS: Brand[] = withStorageUrl([ 
  { name: "Pampanga Provincial Board", logo: "/business_logos/partners/Pampanga Provincial Board.webp" },
  { name: "Angeles City", logo: "/business_logos/partners/Angeles City.webp" },
  { name: "Experience, Live, Love Angeles", logo: "/business_logos/partners/Angeles City_2.webp" },
  { name: "clArk", logo: "/business_logos/partners/clArk.webp" },
  { name: "Clark Development Corporation", logo: "/business_logos/partners/Clark Development Corporation.webp" },
  { name: "Department of Trade & Industry", logo: "/business_logos/partners/Department of Trade & Industry.webp" },
  { name: "DOST Pampanga", logo: "/business_logos/partners/DOST Pampanga.webp" },
  { name: "La Germania", logo: "/business_logos/partners/La Germania.webp" },
  { name: "Peotraco Food Inc.", logo: "/business_logos/partners/Peotraco Food Inc..webp" },
  { name: "Fly Ace Food Service", logo: "/business_logos/partners/Fly Ace Food Service.webp" },
  { name: "Uni-Fab Metal Industries", logo: "/business_logos/partners/Uni-Fab Metal Industries.webp" },
  { name: "Dona Elena", logo: "/business_logos/partners/Dona Elena.webp" },
  { name: "Global Pacific", logo: "/business_logos/partners/Global Pacific.webp" },
  { name: "Kraft Heinz", logo: "/business_logos/partners/Kraft Heinz.webp" },
  { name: "DLA Naturals", logo: "/business_logos/partners/DLA Naturals.webp" },
  { name: "masflex Cookware & Kitchenware", logo: "/business_logos/partners/masflex Cookware & Kitchenware.webp" },
  { name: "Sundae Bar by Echo Treats", logo: "/business_logos/partners/Sundae Bar by Echo Treats.webp" },
  { name: "Eastwest Ageas Insurance", logo: "/business_logos/partners/Eastwest Ageas Insurance.webp" },
  { name: "Cohrep", logo: "/business_logos/partners/Cohrep.webp" },
  { name: "NU Clark", logo: "/business_logos/partners/NU Clark.webp" },
  { name: "City College of Angeles", logo: "/business_logos/partners/City College of Angeles.webp" },
  { name: "Holy Angel University Pampanga", logo: "/business_logos/partners/Holy Angel University Pampanga.webp" },
  { name: "FEU Pampanga", logo: "/business_logos/partners/FEU Pampanga.webp" },
  { name: "Etcor Educational Research Center", logo: "/business_logos/partners/Etcor Educational Research Center.webp" },
  { name: "Pampanga Business Circle", logo: "/business_logos/partners/Pampanga Business Circle.webp" },
  { name: "PCCI Tarlac", logo: "/business_logos/partners/PCCI Tarlac.webp" },
  { name: "Metro Angeles Chamber of Commercial & Industry Inc.", logo: "/business_logos/partners/Metro Angeles Chamber of Commercial & Industry Inc..webp" },
  { name: "BNI Central Luzon 1", logo: "/business_logos/partners/BNI Central Luzon 1.webp" },
  { name: "Wedding Suppliers Association of the Philippines", logo: "/business_logos/partners/Wedding Suppliers Association of the Philippines.webp" },
  { name: "Central Luzon Media Association Pampanga Chapter", logo: "/business_logos/partners/Central Luzon Media Association Pampanga Chapter.webp" },
  { name: "CLTV 36", logo: "/business_logos/partners/CLTV 36.webp" },
  { name: "Reaching Beyond Channels", logo: "/business_logos/partners/Reaching Beyond Channels.webp" },
  { name: "RW 95.1 FM", logo: "/business_logos/partners/RW 95.1 FM.webp" },
  { name: "Pampanga Press Club", logo: "/business_logos/partners/Pampanga Press Club.webp" },
  { name: "JPG Exhibition Booth Rentals", logo: "/business_logos/partners/JPG Exhibition Booth Rentals.webp" },
])

/* ---------------- 2. SPONSORS (13 Brands) ---------------- */
export const SPONSORS: Brand[] = withStorageUrl([ 
  { name: "Savers Group Holdings Inc.", logo: "/business_logos/sponsors/Savers Group Holdings Inc.webp" },
  { name: "GCash", logo: "/business_logos/sponsors/GCash.webp" },
  { name: "Department of Tourism", logo: "/business_logos/sponsors/Department of Tourism.webp" },
  { name: "Central Luzon", logo: "/business_logos/sponsors/Central Luzon.webp" },
  { name: "Clark International Airport Corporation", logo: "/business_logos/sponsors/Clark International Airport Corporation.webp" },
  { name: "Maki Mura Ramen Bar", logo: "/business_logos/sponsors/Maki Mura Ramen Bar.webp" },
  { name: "Crabs n Crack Seafood House", logo: "/business_logos/sponsors/Crabs n Crack Seafood House.webp" },
  { name: "PLDT Enterprise", logo: "/business_logos/sponsors/PLDT Enterprise.webp" },
  { name: "Romac Services & Trading Company Inc.", logo: "/business_logos/sponsors/Romac Services & Trading Company Inc..webp" },
  { name: "AF Ventures Inc.", logo: "/business_logos/sponsors/AF Ventures Inc..webp" },
  { name: "ADM Catering", logo: "/business_logos/sponsors/ADM Catering.webp" },
  { name: "Esme Restaurant", logo: "/business_logos/sponsors/Esme Restaurant.webp" },
  { name: "Asuncion's Private Dining", logo: "/business_logos/sponsors/Asuncion's Private Dining.webp" },
])

/* ---------------- 3. EXHIBITORS (80 Brands) ---------------- */
export const EXHIBITORS: Brand[] = withStorageUrl([
  { name: "bcmm", logo: "/business_logos/exhibitor/bcmm.webp" },
  { name: "Best Western Plus Hotel Subic", logo: "/business_logos/exhibitor/Best Western Plus Hotel Subic.webp" },
  { name: "Best Western Plus Metro Clark", logo: "/business_logos/exhibitor/Best Western Plus Metro Clark.webp" },
  { name: "Cactus Jack Smokehouse", logo: "/business_logos/exhibitor/Cactus Jack Smokehouse.webp" },
  { name: "Cafe Sebastian", logo: "/business_logos/exhibitor/Cafe Sebastian.webp" },
  { name: "Camel", logo: "/business_logos/exhibitor/Camel.webp" },
  { name: "Tiandy", logo: "/business_logos/exhibitor/Tiandy.webp" },
  { name: "Triple LMG Trading", logo: "/business_logos/exhibitor/Triple LMG Trading.webp" },
  { name: "Century Pacific Food Solutions", logo: "/business_logos/exhibitor/Century Pacific Food Solutions - Elevate Enterprises Inc..webp" },
  { name: "Polland", logo: "/business_logos/exhibitor/Polland.webp" },
  { name: "Condura", logo: "/business_logos/exhibitor/Condura.webp" },
  { name: "Whirlpool", logo: "/business_logos/exhibitor/Whirlpool.webp" },
  { name: "Viktor Brew + Bar", logo: "/business_logos/exhibitor/Viktor Brew + Bar.webp" },
  { name: "Dayap Philippines", logo: "/business_logos/exhibitor/Dayap Philippines.webp" },
  { name: "Sundae Bar By Echo Treats", logo: "/business_logos/exhibitor/Sundae Bar By Echo Treats.webp" },
  { name: "Mekeni", logo: "/business_logos/exhibitor/Mekeni.webp" },
  { name: "Dara Consulting", logo: "/business_logos/exhibitor/Dara Consulting.webp" },
  { name: "Consistent Frozen Solutions", logo: "/business_logos/exhibitor/Consistent Frozen Solutions.webp" },
  { name: "Angeles City", logo: "/business_logos/exhibitor/Angeles City.webp" },
  { name: "Migoy's Burger", logo: "/business_logos/exhibitor/Migoy's Burger.webp" },
  { name: "Isabel Frozen Products", logo: "/business_logos/exhibitor/Isabel Frozen Products.webp" },
  { name: "Hapag Scan Order Pay", logo: "/business_logos/exhibitor/Hapag Scan Order Pay.webp" },
  { name: "Casa Esmeralda", logo: "/business_logos/exhibitor/Casa Esmeralda.webp" },
  { name: "Metrobank", logo: "/business_logos/exhibitor/Metrobank.webp" },
  { name: "gud is better", logo: "/business_logos/exhibitor/gud is better.webp" },
  { name: "Hannah Marielle's Bakes & Cakes", logo: "/business_logos/exhibitor/Hannah Marielle's Bakes & Cakes.webp" },
  { name: "Trisco Foods", logo: "/business_logos/exhibitor/Trisco Foods.webp" },
  { name: "Venezia", logo: "/business_logos/exhibitor/Venezia.webp" },
  { name: "Switch Ecomobility", logo: "/business_logos/exhibitor/Switch Ecomobility.webp" },
  { name: "WiiArts", logo: "/business_logos/exhibitor/WiiArts.webp" },
  { name: "Home Kitchen", logo: "/business_logos/exhibitor/Home Kitchen.webp" },
  { name: "Jack's Pool Bar", logo: "/business_logos/exhibitor/Jack's Pool Bar.webp" },
  { name: "Luka's Butter Steaks", logo: "/business_logos/exhibitor/Luka's Butter Steaks.webp" },
  { name: "Maki Mura", logo: "/business_logos/exhibitor/Maki Mura.webp" },
  { name: "1st Mega Saver", logo: "/business_logos/exhibitor/1st Mega Saver.webp" },
  { name: "Namari Japanese Bistro", logo: "/business_logos/exhibitor/Namari Japanese Bistro.webp" },
  { name: "Makuru Japanese Wraps & Rolls", logo: "/business_logos/exhibitor/Makuru Japanese Wraps & Rolls.webp" },
  { name: "Monaco", logo: "/business_logos/exhibitor/Monaco.webp" },
  { name: "Spencers Fusion", logo: "/business_logos/exhibitor/Spencers Fusion.webp" },
  { name: "Caution Coffee", logo: "/business_logos/exhibitor/Caution Coffee.webp" },
  { name: "Prime Pacific Foods Corporation", logo: "/business_logos/exhibitor/Prime Pacific Foods Corporation.webp" },
  { name: "Legend Hong Kong Seafood Restaurant", logo: "/business_logos/exhibitor/Legend Hong Kong Seafood Restaurant.webp" },
  { name: "pyc Foods Corporation", logo: "/business_logos/exhibitor/pyc Foods Corporation.webp" },
  { name: "LG", logo: "/business_logos/exhibitor/LG.webp" },
  { name: "Seachamp", logo: "/business_logos/exhibitor/Seachamp.webp" },
  { name: "Liway Enterprises Inc.", logo: "/business_logos/exhibitor/Liway Enterprises Inc..webp" },
  { name: "smart living", logo: "/business_logos/exhibitor/smart living.webp" },
  { name: "Kasuko", logo: "/business_logos/exhibitor/Kasuko.webp" },
  { name: "Savers Industrial & Building Solutions", logo: "/business_logos/exhibitor/Savers Industrial & Building Solutions.webp" },
  { name: "Savers Group Holdings Inc.", logo: "/business_logos/exhibitor/Savers Group Holdings Inc.webp" },
  { name: "Sunshine Clean Greens", logo: "/business_logos/exhibitor/Sunshine Clean Greens.webp" },
  { name: "Farm to Table", logo: "/business_logos/exhibitor/Farm to Table.webp" },
  { name: "Asuncion's", logo: "/business_logos/exhibitor/Asuncion's Private Dining.webp" },
  { name: "AF Ventures Inc.", logo: "/business_logos/exhibitor/AF Ventures Inc..webp" },
  { name: "ADM Catering", logo: "/business_logos/exhibitor/ADM Catering.webp" },
  { name: "Esme", logo: "/business_logos/exhibitor/Esme Restaurant.webp" },
  { name: "Fortune Tea House", logo: "/business_logos/exhibitor/Fortune Tea House.webp" },
  { name: "Tecnogas Technik", logo: "/business_logos/exhibitor/Tecnogas Technik.webp" },
  { name: "Allie Steel Premium Metal Cabinet", logo: "/business_logos/exhibitor/Allie Steel Premium Metal Cabinet.webp" },
  { name: "BNI Central Luzon 1", logo: "/business_logos/exhibitor/BNI Central Luzon 1.webp" },
  { name: "Elektro Kuche", logo: "/business_logos/exhibitor/Elektro Kuche.webp" },
  { name: "Fujidenzo", logo: "/business_logos/exhibitor/Fujidenzo.webp" },
  { name: "JDNB Enterprise Corporation", logo: "/business_logos/exhibitor/JDNB Enterprise Corporation.webp" },
  { name: "Lugaw ni Bossing", logo: "/business_logos/exhibitor/Lugaw ni Bossing.webp" },
  { name: "American Ribs & Wings", logo: "/business_logos/exhibitor/American Ribs & Wings.webp" },
  { name: "kape kaia", logo: "/business_logos/exhibitor/kape kaia.webp" },
  { name: "cloud9", logo: "/business_logos/exhibitor/cloud9.webp" },
  { name: "92 parameters", logo: "/business_logos/exhibitor/92 parameters.webp" },
  { name: "leaf & bean slow bar", logo: "/business_logos/exhibitor/leaf & bean slow bar.webp" },
  { name: "Ceremo", logo: "/business_logos/exhibitor/Ceremo.webp" },
  { name: "Lilim", logo: "/business_logos/exhibitor/Lilim.webp" },
  { name: "Artisanos Specialty Coffee & Matcha", logo: "/business_logos/exhibitor/Artisanos Specialty Coffee & Matcha.webp" },
  { name: "hakone Matcha + Mochi", logo: "/business_logos/exhibitor/hakone Matcha + Mochi.webp" },
  { name: "kismet", logo: "/business_logos/exhibitor/kismet.webp" },
  { name: "kokorobi", logo: "/business_logos/exhibitor/kokorobi.webp" },
  { name: "matchabaa", logo: "/business_logos/exhibitor/matchabaa.webp" },
  { name: "Slow Sunday", logo: "/business_logos/exhibitor/Slow Sunday.webp" },
  { name: "Whisk & Sip", logo: "/business_logos/exhibitor/Whisk & Sip.webp" },
  { name: "Silung Coffee", logo: "/business_logos/exhibitor/Silung Coffee.webp" },
  { name: "M2", logo: "/business_logos/exhibitor/M2.webp" },
])